units_type: character
feature_source: librosa
feature_type: logmel
data:
    name: aishell
    vocab: data/aishell/grapheme_table.txt
    left_context_width: 3
    right_context_width: 0
    feature_dim: 128
    subsample: 3
    apply_cmvn: False
    max_input_length: 410  # 最大490
    max_target_length: 42  # 最大44
    batch_size: 4
    short_first: False
    shuffle: True
    train: data/aishell/train.csv
    dev: data/aishell/dev.csv
    test: data/aishell/test.csv
model:
    type: transducer
    enc:
        type: attention
        max_input_length: 410
        left_context: 10
        right_context: 2
        d_inner: 1024
        n_head: 8
        d_model: 512
        d_head: 64
        n_layer: 4
    dec:
        type: attention
        max_target_length: 42
        hidden_size:
        output_size:
        d_inner: 1024
        n_head: 8
        d_model: 512
        d_head: 64
        n_layer: 1
    joint:
        input_size: 1024
        inner_size: 1024
    vocab_size: 4334
    share_weight: False
    feature_dim:
    dropout: 0.1
training:
    exp_name: test
    load_model: False
    load_encoder: False
    load_decoder: False
    eval_or_not: True
    seed: 1
    num_gpu: 1
    epochs: 30
    max_grad_norm: 200
    visualization: True
    show_interval: 100
    save_model: 4e_1d_1024
optim:
    type: sgd
    lr: 0.00025
    momentum: 0.9
    decay_ratio: 0.1
    weight_decay: 0
    begin_to_adjust_lr: 0
